---
- tags: [arch]
  block:
  - tags: [aur]
    block:
    - include_tasks: aur_apps.yml
    - include_tasks: setup_aur.yml
    - include_tasks: update_aur.yml
  - include_tasks: docker.yml
    tags: [arch_docker]
  - include_tasks: update.yml
    tags: [update]
