---
- name: Update package database "pacman -Sy"
  become: yes
  community.general.pacman:
    update_cache: yes

- name: Upgrade native packages "pacman -Su"
  become: yes
  community.general.pacman:
    upgrade: yes
