---
- name: Ensure the {{ docker_user }} user
  ansible.builtin.user:
    name: "{{ docker_user }}"
    create_home: yes
    group: docker
    uid: 900

- name: Ensure Docker daemon is enabled and running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
