version: "3.5"
services:
  jellyfin:
    image: {{ image }}:{{ tag }}
    container_name: jellyfin
    user: {{ jellyfin_uid }}:{{ jellyfin_gid }}
    volumes:
      - {{ jellyfin_config }}:/config
      - {{ jellyfin_cache }}:/cache
      - {{ jellyfin_data }}:/media
    ports:
      - {{ jellyfin_http_port}}:{{jellyfin_http_port}}
    restart: "unless-stopped"
